
name: Self-Healing Playwright Tests CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build image
              run: docker build -t self-healing-playwright-tests .

            - name: Run tests
              env:
                GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
              run: docker run --rm -e GROQ_API_KEY=$GROQ_API_KEY self-healing-playwright-tests pytest tests/


            - name: login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


            - name: Push image to Docker Hub
              run: |
                docker tag self-healing-playwright-tests ${{ secrets.DOCKER_USERNAME }}/self-healing-playwright-tests:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/self-healing-playwright-tests:latest

